### ISSUE TITLE
Armor optimisation logic issue

### ISSUE THREAD

**Issue by TheCoolerMaz** [threeskimo/Remnant-2-Armor-Calculator#1]
Issue:
Whatever algorithm is being used to optimize the armor is looking to max out armor even when there are lighter armors with more efficient armor / weight rating.

This is easily replicable by going between 87.9 and 88. By doing this the armor rating decreases from 173 to 169.9.
The logic seems to be aiming to maximize weight, not maximise armor within the threshold.

Not sure how much of an update is needed to fix this but would just be the cherry on top of a pretty good tool as it is.
Thanks.

**Comment by threeskimo** [comment]
Thanks. There are better Remnant 2 armor calculators out there now (e.g. https://scouthunter.github.io/R2AG/) so I do not plan to continue to update this project. Sorry.
